### ISSUE TITLE
Configure taglib with spring

### ISSUE THREAD

**Issue by tveimo** [lifus/wro4j-runtime-taglib#2]
It would be very convenient if the taglib could be configured through Spring. This is especially handy when the wro4j filter and manager is itself configured through Spring.

**Comment by tveimo** [comment]
Maybe an instance of OptimizedResourcesRootProvider could be configured through spring?

**Comment by tveimo** [comment]
If wro4j is configured through spring, then the filter is often an instance of the dynamic proxy class org.springframework.web.filter.DelegatingFilterProxy. Additionally, there's no instance of WroServletContextListener.

**Comment by lifus** [comment]
[WroManagerFactory](https://github.com/wro4j/wro4j/blob/1.7.x/wro4j-core/src/main/java/ro/isdc/wro/manager/factory/WroManagerFactory.java) should be initialized before [TaglibContext](https://github.com/lifus/wro4j-runtime-taglib/blob/master/src/main/java/com/github/lifus/wro4j_runtime_taglib/context/TaglibContext.java) because [TaglibContextFactory](https://github.com/lifus/wro4j-runtime-taglib/blob/master/src/main/java/com/github/lifus/wro4j_runtime_taglib/context/TaglibContextFactory.java) decorates WroManagerFactory. i.e. [WroServletContextListener](https://github.com/wro4j/wro4j/blob/1.7.x/wro4j-core/src/main/java/ro/isdc/wro/http/WroServletContextListener.java) might still be required to create WroManagerFactory unless there would be a singleton bean for WroManagerFactory that would be injected/autowired.

Unfortunately, DelegatingFilterProxy [doesn't provide a way to get a bean class name(s)](http://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/filter/DelegatingFilterProxy.html) and so we couldn't be sure that it actually delegates to WroFilter. [findWebApplicationContext is protected](http://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/filter/DelegatingFilterProxy.html#findWebApplicationContext--) i.e. it would require some spring-specific code and I believe that there might be a better solution:

I'm going to support something like this:

```
optimizedResourcesRootStrategy=predefined
optimizedResourcesRoot=/wro/
```

this class should probably also have a setter to allow setter injection.

**Comment by tveimo** [comment]
Would it be an option to configure the TaglibContextFactory through spring as well?

**Comment by lifus** [comment]
Actually, It might be already possible to initialize TaglibContext through spring because [TaglibContext.initialize](https://github.com/lifus/wro4j-runtime-taglib/blob/master/src/main/java/com/github/lifus/wro4j_runtime_taglib/context/TaglibContext.java#L30) accepts ServletContext.
There is a prerequisite, though: WroManagerFactory [should already be stored as an attribute](https://github.com/wro4j/wro4j/blob/1.7.x/wro4j-core/src/main/java/ro/isdc/wro/http/support/ServletContextAttributeHelper.java#L196). That's the reason [why I suggested to use WroServletContextListener](https://github.com/wro4j/wro4j/blob/1.7.x/wro4j-core/src/main/java/ro/isdc/wro/http/WroServletContextListener.java#L59)
Also, [WroContextFilter](https://github.com/wro4j/wro4j/blob/1.7.x/wro4j-core/src/main/java/ro/isdc/wro/http/WroContextFilter.java#L61) is required to provide [Context](https://github.com/wro4j/wro4j/blob/1.7.x/wro4j-core/src/main/java/ro/isdc/wro/config/Context.java) at runtime.

**Comment by tveimo** [comment]
Do you have an example setting up a TaglibContext in spring? The crucial constructors in TaglibContext and TaglibContextFactory are package protected, making it a bit hard to initialize outside.

**Comment by lifus** [comment]
Unfortunately, I don't have such an example. I may create one though.
Constructors in TaglibContext and TaglibContextFactory are package protected because TaglibContext should be initialized through [TaglibContext.initialize](https://github.com/wro4j/wro4j-runtime-taglib/blob/master/src/main/java/com/github/lifus/wro4j_runtime_taglib/context/TaglibContext.java#L30) so that it would be possible to retrieve TaglibContext using [TaglibContext.get](https://github.com/wro4j/wro4j-runtime-taglib/blob/master/src/main/java/com/github/lifus/wro4j_runtime_taglib/context/TaglibContext.java#L43)
I'm not entirely sure how do you want to configure taglib with spring. I believe that one way to do it is to create [ServletContextAware](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/context/ServletContextAware.html) bean and initialize TaglibContext there. As I mentioned before, WroManagerFactory should be initialized before TaglibContext and "persisted" in ServletContext as well.

**Comment by tveimo** [comment]
Ok, got it set up now, but unfortunately, in DefaultOptimizedResourcesRootProvider.getFilterRegistrations(), servletContext.getServletRegistrations() is called, and this method cannot be called from outside of a servlet listener (throws an UnsupportedOperationException).

So I guess using a different resources root provider that just takes the config from properties as you suggested above is probably the best way forward. I had success with a dummy setup;

package com.github.lifus.wro4j_runtime_taglib.model.resource.uri.root;

import javax.servlet.FilterRegistration;
import javax.servlet.ServletContext;
import ro.isdc.wro.http.WroFilter;

public final class SpringOptimizedResourcesRootProvider extends AbstractOptimizedResourcesRootProvider {

  public SpringOptimizedResourcesRootProvider(final ServletContext servletContext) { }

  @Override
  protected String findOutRoot() {
      return "/resources/wro/";
  }
}

**Comment by tveimo** [comment]
Works well with 0.1.3-SNAPSHOT, thx!

**Comment by lifus** [comment]
Closing this one for now as I'm going to include current implementation as is in 0.2.0 release. Feel free to reopen this issue or create a more specific one
